blank_issues_enabled: false
contact_links:
    - name: ðŸ“ƒ Documentation
      url: https://docs.agora.io/en/api-reference?platform=react-native
      about: Usage documentation of the interface.
    - name: ðŸ“ƒ Documentation in china
      url: http://docs-im-beta.easemob.com/document/react-native/quickstart.html
      about: Usage documentation of the interface.
    - name: ðŸ¤” Questions and Help
      url: https://docs.agora.io/en/help
      about: Please report documentation issues in the website repository.
    - name: ðŸš€ Discussions and Proposals
      url: https://github.com/easemob/react-native-chat-library/discussions-and-proposals
      about: Discuss the future of React Native Chat SDK in the React Native community's discussions and proposals repository.
